### PR TITLE
Fixed email address to root@siketyan.dev

### PR DESCRIPTION
**Pull request by kichi2004**
close: #37

### CODE REVIEW

**Comment by Siketyan** [comment]
@kichi2004 
Thank you for contributing!
I am working to fix CI/CDs for confirming your pull request #39 #40 .
Just a sec to merge this.

**Comment by Siketyan** [comment]
@kichi2004 
All done!
Could you rebase your `kichi2004:#37` branch to current my `Siketyan:master` ?

**Comment by Siketyan** [comment]
I recommend force pushing to keep the tree clean.

**Comment by kichi2004** [comment]
@Siketyan done!

**Pull request merged**
